# Generated by Django 3.2.8 on 2021-10-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20211026_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.FileField(upload_to='media/%Y/%m/'),
        ),
    ]
